# Generated by Django 3.2.8 on 2021-10-27 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tweets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='isim')),
                ('text', models.TextField(max_length=144, verbose_name='Mesaj')),
                ('completed', models.BooleanField(verbose_name='durum')),
            ],
        ),
    ]
